apiVersion: v1
kind: PersistentVolume
metadata:
  name: mininfs
spec:
  capacity:
    storage: 85Gi 
  accessModes:
  - ReadWriteMany 
  nfs: 
    path: /mininfs
    server: mininfs.zircon.local
  persistentVolumeReclaimPolicy: Recycle
