apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - name: "http"
      port: 80
      protocol: "TCP"
      nodePort: 30080
    - name: "https"
      port: 443
      protocol: "TCP"
      nodePort: 30443
  type: "NodePort"
        #  externalName: "http://nginx.zircon.local"

